// ─── EMOJ     I & ICON DATA ─────────────────────────────────────────
// Single source of truth for every emoji/icon used in the UI.
const ICONS = {
    // Default emojis for each entity type
    defaultDial:     '😀',
    defaultGroup:    '📁',
    defaultTab:      '🗂',
    faviconFallback: '🌐',  // shown when favicon / custom image fails

    // UI affordances
    edit:    '✏️',
    delete:  '🗑',
    search:  '🔍',

    // Status / toast indicators
    ok:      '✅',
    warn:    '⚠️',
    error:   '❌',
    undo:    '↩️',
    loading: '⏳',

    // Todo list icons
    defaultTodoList: '📋',
    check:           '☑',
    uncheck:         '☐',
    moveTop:         '⤒',
    moveBottom:      '⤓',
};

const EMOJI_CATEGORIES = [
    { label: '😀 Smileys & Emotion', emojis: ['😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃','🫠','😉','😊','😇','🥰','😍','🤩','😘','😗','😚','😙','🥲','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🫡','🤫','🤔','🫢','🤐','🥸','😐','😑','😶','🫥','😏','😒','🙄','😬','🤥','🫨','😌','😔','😪','🤤','😴','😷','🤒','🤕','🤢','🤮','🤧','🥵','🥶','🥴','😵','🤯','🤠','🥳','🥸','😎','🤓','🧐','😕','🫤','😟','🙁','☹️','😮','😯','😲','😳','🥺','🫣','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻','👽','👾','🤖','😺','😸','😹','😻','😼','😽','🙀','😿','😾','🙂‍↔️','🙂‍↕️','🫩'] },
    { label: '👋 People & Body', emojis: ['👋','🤚','🖐','✋','🖖','🫱','🫲','🫳','🫴','👌','🤌','🤏','✌️','🤞','🫰','🤟','🤘','🤙','👈','👉','👆','🖕','👇','☝️','🫵','👍','👎','✊','👊','🤛','🤜','👏','🙌','🫶','👐','🤲','🤝','🙏','✍️','💅','🤳','💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🫀','🫁','🧠','🦷','🦴','👀','👁','👅','👄','🫦','👶','🧒','👦','👧','🧑','👱','👨','🧔','👩','🧓','👴','👵','🙍','🙎','🙅','🙆','💁','🙋','🧏','🙇','🤦','🤷','💆','💇','🚶','🧍','🧎','🏃','💃','🕺','🕴','👫','👬','👭','👨‍👩‍👦','👨‍👩‍👧','👪','🤰','🤱','👼','🎅','🤶','🦸','🦹','🧙','🧚','🧛','🧜','🧝','🧞','🧟','🧌','💏','💑','🫷','🫸','🫆','🧑‍🧒','🧑‍🧒‍🧒','🧑‍🧑‍🧒','🧑‍🧑‍🧒‍🧒'] },
    { label: '🐶 Animals & Nature', emojis: ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐻‍❄️','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐔','🐧','🐦','🐤','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🪱','🐛','🦋','🐌','🐞','🐜','🪲','🦟','🦗','🕷','🦂','🐢','🐍','🦎','🦖','🦕','🐙','🦑','🦐','🦞','🦀','🦪','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🐊','🐅','🐆','🦓','🦍','🦧','🦣','🐘','🦛','🦏','🐪','🐫','🦒','🦘','🦬','🐃','🐂','🐄','🐎','🐖','🐏','🐑','🦙','🐐','🦌','🐕','🐩','🦮','🐈','🐈‍⬛','🪶','🐓','🦃','🦤','🦚','🦜','🦢','🦩','🕊','🐇','🦝','🦨','🦡','🦫','🦦','🦥','🐁','🐀','🐿','🦔','🐾','🐉','🐲','🌵','🎄','🌲','🌳','🌴','🪵','🌱','🌿','☘️','🍀','🎍','🪴','🎋','🍃','🍂','🍁','🪺','🪹','🍄','🐚','🪸','🪨','🌾','💐','🌷','🌹','🥀','🪷','🌺','🌸','🌼','🌻','🌞','🌝','🌛','🌜','🌚','🌕','🌖','🌗','🌘','🌑','🌒','🌓','🌔','🌙','🌟','⭐','🌠','🌌','☀️','🌤','⛅','🌥','☁️','🌦','🌧','⛈','🌩','🌨','❄️','☃️','⛄','🌬','💨','🌀','🌈','🌂','☂️','☔','⛱','⚡','❗','🌊','🌫','🌬','🫎','🫏','🪽','🐦‍⬛','🪿','🪼','🪻','🐦‍🔥','🪾'] },
    { label: '🍎 Food & Drink', emojis: ['🍏','🍎','🍐','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍈','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🍆','🥑','🥦','🥬','🥒','🌶','🫑','🧄','🧅','🥔','🍠','🫘','🥐','🥯','🍞','🥖','🥨','🧀','🥚','🍳','🧈','🥞','🧇','🥓','🥩','🍗','🍖','🌭','🍔','🍟','🍕','🫓','🥪','🥙','🧆','🌮','🌯','🫔','🥗','🥘','🫕','🥫','🍝','🍜','🍲','🍛','🍣','🍱','🥟','🦪','🍤','🍙','🍚','🍘','🍥','🥮','🍢','🧁','🍡','🍧','🍨','🍦','🥧','🧁','🍰','🎂','🍮','🍭','🍬','🍫','🍿','🍩','🍪','🌰','🥜','🍯','🧃','🥤','🧋','🍵','☕','🫖','🍺','🍻','🥂','🍷','🫗','🥃','🍸','🍹','🧉','🍾','🧊','🥄','🍴','🍽','🥢','🧂','🫚','🫛','🍋‍🟩','🍄‍🟫','🫜'] },
    { label: '✈️ Travel & Places', emojis: ['🚗','🚕','🚙','🚌','🚎','🏎','🚓','🚑','🚒','🚐','🛻','🚚','🚛','🚜','🏍','🛵','🛺','🚲','🛴','🛹','🛼','🚏','🛣','🛤','⛽','🛞','🚨','🚥','🚦','🛑','🚧','⚓','🛟','⛵','🚤','🛥','🛳','⛴','🚢','✈️','🛩','🛫','🛬','🪂','💺','🚁','🚟','🚠','🚡','🛸','🚀','🛶','🏖','🏔','⛰','🌋','🗻','🏕','🏗','🧱','🪨','🪵','🛖','🏘','🏚','🏠','🏡','🏢','🏣','🏤','🏥','🏦','🏨','🏩','🏪','🏫','🏭','🏯','🏰','💒','🗼','🗽','⛪','🕌','🛕','🕍','⛩','🕋','⛲','⛺','🌁','🌃','🏙','🌄','🌅','🌆','🌇','🌉','🗺','🧭','🌐','🗾','🏔','🌏','🌍','🌎','🪐','💫','⭐','🌟','✨','⚡','☄️','🌞','🌝','🌙','🌛','🌜','🌚'] },
    { label: '⚽ Activities', emojis: ['⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱','🪀','🏓','🏸','🏒','🥍','🏑','🥅','⛳','🪁','🏹','🎣','🤿','🥊','🥋','🎽','🛹','🛼','🛷','⛸','🥌','🎿','⛷','🏂','🪂','🏋','🤼','🤸','⛹','🤺','🏇','🧘','🏄','🏊','🤽','🚣','🧗','🚵','🚴','🏆','🥇','🥈','🥉','🏅','🎖','🏵','🎗','🎫','🎟','🎪','🤹','🎭','🩰','🎨','🎬','🎤','🎧','🎼','🎵','🎶','🪘','🥁','🪗','🎷','🎺','🎸','🪕','🎻','🎲','♟','🎯','🎳','🎮','🎰','🧩','🪄','🃏','🀄','🎴'] },
    { label: '💡 Objects', emojis: ['📱','💻','🖥','🖨','⌨️','🖱','🖲','💽','💾','💿','📀','📷','📸','📹','🎥','📽','🎞','📞','☎️','📟','📠','📺','📻','🧭','⏱','⏰','⏲','⏳','📡','🔋','🪫','🔌','💡','🔦','🕯','🪔','🧱','🪞','🪟','🛏','🛋','🪑','🚽','🪠','🚿','🛁','🪤','🧴','🧷','🧹','🧺','🧻','🪣','🧼','🫧','🪥','🧽','🪒','🧴','🧰','🪛','🔧','🔨','⚒','🛠','⛏','🪚','🔩','🪤','🧲','💣','🪓','🔪','🗡','⚔️','🛡','🪃','🪝','🧲','🪜','🧪','🧫','🧬','🔭','🔬','🩻','🩺','💊','💉','🩸','🩹','🩼','🩻','🏥','🪤','🧸','🪅','🪆','🖼','🪞','📦','📫','📪','📬','📭','📮','📯','📜','📋','📁','📂','🗂','📅','📆','📇','📈','📉','📊','📋','📌','📍','📎','🖇','📏','📐','✂️','🗃','🗄','🗑','🔒','🔓','🔏','🔐','🔑','🗝','🔨','🪓','⛏','⚒','🛠','🗜','⚙️','🗡','⚔️','🛡','🪃','🏹','🪚','🔧','🪛','🔩','🪤','🧲','🪜','🪭','🪮','🪇','🪈','⛓️‍💥','🪉','🪏'] },
    { label: '💬 Symbols', emojis: ['❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔','❤️‍🔥','❤️‍🩹','❣️','💕','💞','💓','💗','💖','💘','💝','💟','☮️','✝️','☪️','🕉','☸️','✡️','🔯','🕎','☯️','☦️','🛐','⛎','♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓','🆔','⚛️','🉑','☢️','☣️','📴','📳','🈶','🈚','🈸','🈺','🈷️','✴️','🆚','💮','🉐','㊙️','㊗️','🈴','🈵','🈹','🈲','🅰️','🅱️','🆎','🆑','🅾️','🆘','❌','⭕','🛑','⛔','📛','🚫','💯','💢','♨️','🚷','🚯','🚳','🚱','🔞','📵','🚭','❗','❕','❓','❔','‼️','⁉️','🔅','🔆','〽️','⚠️','🚸','🔱','⚜️','🔰','♻️','✅','🈯','💹','❎','🌐','💠','Ⓜ️','🌀','💤','🏧','🚾','♿','🅿️','🛗','🈳','🈹','🚺','🚹','🚼','⚧','🚻','🚮','🎦','📶','🈁','🔣','ℹ️','🔤','🔡','🔠','🆖','🆗','🆙','🆒','🆕','🆓','0️⃣','1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟','🔢','▶️','⏸','⏹','⏺','⏭','⏮','⏩','⏪','⏫','⏬','◀️','🔼','🔽','➡️','⬅️','⬆️','⬇️','↗️','↘️','↙️','↖️','↕️','↔️','↩️','↪️','⤴️','⤵️','🔀','🔁','🔂','🔃','🎵','🎶','➕','➖','➗','✖️','💲','💱','™️','©️','®️','〰️','➰','➿','🔚','🔙','🔛','🔜','🔝','✔️','☑️','🔘','🔲','🔳','▪️','▫️','◾','◽','◼️','◻️','⬛','⬜','🟥','🟧','🟨','🟩','🟦','🟪','🟫','🔶','🔷','🔸','🔹','🔺','🔻','💠','🔘','🔲','🪯','🛜','🩷','🩵','🩶','🫟'] },
    { label: '🏁 Flags', emojis: ['🏳️','🏴','🏴‍☠️','🚩','🏁','🎌','🏳️‍🌈','🏳️‍⚧️','🇺🇳','🇦🇫','🇦🇱','🇩🇿','🇦🇩','🇦🇴','🇦🇮','🇦🇬','🇦🇷','🇦🇲','🇦🇼','🇦🇺','🇦🇹','🇦🇿','🇧🇸','🇧🇭','🇧🇩','🇧🇧','🇧🇾','🇧🇪','🇧🇿','🇧🇯','🇧🇲','🇧🇹','🇧🇴','🇧🇦','🇧🇼','🇧🇷','🇻🇬','🇧🇳','🇧🇬','🇧🇫','🇧🇮','🇰🇭','🇨🇲','🇨🇦','🇨🇻','🇧🇶','🇰🇾','🇨🇫','🇹🇩','🇨🇱','🇨🇳','🇨🇴','🇰🇲','🇨🇬','🇨🇩','🇨🇷','🇨🇮','🇭🇷','🇨🇺','🇨🇼','🇨🇾','🇨🇿','🇩🇰','🇩🇯','🇩🇲','🇩🇴','🇪🇨','🇪🇬','🇸🇻','🇬🇶','🇪🇷','🇪🇪','🇸🇿','🇪🇹','🇫🇰','🇫🇴','🇫🇯','🇫🇮','🇫🇷','🇬🇫','🇵🇫','🇬🇦','🇬🇲','🇬🇪','🇩🇪','🇬🇭','🇬🇮','🇬🇷','🇬🇱','🇬🇩','🇬🇵','🇬🇺','🇬🇹','🇬🇬','🇬🇳','🇬🇼','🇬🇾','🇭🇹','🇭🇳','🇭🇰','🇭🇺','🇮🇸','🇮🇳','🇮🇩','🇮🇷','🇮🇶','🇮🇪','🇮🇲','🇮🇱','🇮🇹','🇯🇲','🇯🇵','🇯🇪','🇯🇴','🇰🇿','🇰🇪','🇰🇮','🇽🇰','🇰🇼','🇰🇬','🇱🇦','🇱🇻','🇱🇧','🇱🇸','🇱🇷','🇱🇾','🇱🇮','🇱🇹','🇱🇺','🇲🇴','🇲🇬','🇲🇼','🇲🇾','🇲🇻','🇲🇱','🇲🇹','🇲🇭','🇲🇶','🇲🇷','🇲🇺','🇾🇹','🇲🇽','🇫🇲','🇲🇩','🇲🇨','🇲🇳','🇲🇪','🇲🇸','🇲🇦','🇲🇿','🇲🇲','🇳🇦','🇳🇷','🇳🇵','🇳🇱','🇳🇨','🇳🇿','🇳🇮','🇳🇪','🇳🇬','🇳🇺','🇳🇫','🇲🇰','🇲🇵','🇳🇴','🇴🇲','🇵🇰','🇵🇼','🇵🇸','🇵🇦','🇵🇬','🇵🇾','🇵🇪','🇵🇭','🇵🇳','🇵🇱','🇵🇹','🇵🇷','🇶🇦','🇷🇪','🇷🇴','🇷🇺','🇷🇼','🇰🇳','🇱🇨','🇻🇨','🇼🇸','🇸🇲','🇸🇹','🇸🇦','🇸🇳','🇷🇸','🇸🇨','🇸🇱','🇸🇬','🇸🇽','🇸🇰','🇸🇮','🇸🇧','🇸🇴','🇿🇦','🇬🇸','🇸🇸','🇪🇸','🇱🇰','🇸🇩','🇸🇷','🇸🇪','🇨🇭','🇸🇾','🇹🇼','🇹🇯','🇹🇿','🇹🇭','🇹🇱','🇹🇬','🇹🇰','🇹🇴','🇹🇹','🇹🇳','🇹🇷','🇹🇲','🇹🇨','🇹🇻','🇺🇬','🇺🇦','🇦🇪','🇬🇧','🏴󠁧󠁢󠁥󠁮󠁧󠁿','🏴󠁧󠁢󠁳󠁣󠁴󠁿','🏴󠁧󠁢󠁷󠁬󠁳󠁿','🇺🇸','🇻🇮','🇺🇾','🇺🇿','🇻🇺','🇻🇦','🇻🇪','🇻🇳','🇼🇫','🇾🇪','🇿🇲','🇿🇼','🇨🇶'] },
];

// Flat list for random picking (all emojis except flags)
const EMOJI_LIST = EMOJI_CATEGORIES.slice(0, -1).flatMap(c => c.emojis);
const GROUP_EMOJIS = ['📁','💼','🌐','⭐','🔖','🏠','🎯','🚀','🎮','💡','📚','🛍','🎵','🎬','✈️','🌍','🔥','💎','⚡','🧩','🏆','❤️','🍀','🔐','🗂','📊','📱','💻','🌙','🌈','🎨','🧪','🦋','🌻','🐉','🪼','🐦‍🔥','🩷','🛜'];

// Keyword fallback for emoji search (primary names used by emojiMatchesFilter)
const EMOJI_KEYWORDS = {
    '😀':'grinning','😃':'smiley','😄':'smile','😁':'grin','😆':'laughing','😅':'sweat smile','🤣':'rofl','😂':'joy','🙂':'slightly smiling','😉':'wink','😊':'blush','😇':'innocent','🥰':'smiling hearts','😍':'heart eyes','🤩':'star struck','😘':'kiss','😗':'kissing','😚':'kissing closed eyes','😙':'kissing smiling eyes','😋':'yum','😛':'stuck out tongue','😜':'winking tongue','🤪':'zany','😝':'squinting tongue','🤑':'money mouth','🤗':'hugging','🤔':'thinking','🤐':'zipper mouth','😐':'neutral','😑':'expressionless','😶':'no mouth','😏':'smirk','😒':'unamused','🙄':'eye roll','😬':'grimace','😌':'relieved','😔':'pensive','😪':'sleepy','🤤':'drooling','😴':'sleeping','😷':'mask','🤒':'thermometer face','🤕':'head bandage','🤢':'nauseated','🤮':'vomiting','🤧':'sneezing','🥵':'hot','🥶':'cold','🥴':'woozy','😵':'dizzy','🤯':'exploding head','🤠':'cowboy','🥳':'partying','😎':'sunglasses','🤓':'nerd','🧐':'monocle','😕':'confused','😟':'worried','🙁':'frowning','☹️':'frowning face','😮':'open mouth','😯':'hushed','😲':'astonished','😳':'flushed','🥺':'pleading','😦':'frowning open mouth','😧':'anguished','😨':'fearful','😰':'anxious sweat','😥':'sad relieved','😢':'cry','😭':'loudly crying','😱':'screaming','😖':'confounded','😣':'persevering','😞':'disappointed','😓':'downcast sweat','😩':'weary','😫':'tired','🥱':'yawning','😤':'huffing','😡':'pouting','😠':'angry','🤬':'cursing','😈':'smiling devil','👿':'angry devil','💀':'skull','☠️':'skull crossbones','💩':'poop','🤡':'clown','👹':'ogre','👺':'goblin','👻':'ghost','👽':'alien','👾':'space invader','🤖':'robot',
    '👋':'wave','✋':'raised hand','👌':'ok hand','✌️':'victory','👍':'thumbs up','👎':'thumbs down','✊':'raised fist','👊':'oncoming fist','👏':'clapping','🙏':'folded hands','💪':'muscle','👀':'eyes','❤️':'heart red','🧡':'heart orange','💛':'heart yellow','💚':'heart green','💙':'heart blue','💜':'heart purple','🖤':'heart black','🤍':'heart white','💔':'broken heart','💕':'two hearts','💞':'revolving hearts','💓':'beating heart','💗':'growing heart','💖':'sparkling heart','💘':'heart arrow','💝':'heart ribbon',
    '🐶':'dog','🐱':'cat','🐭':'mouse','🐹':'hamster','🐰':'rabbit','🦊':'fox','🐻':'bear','🐼':'panda','🐨':'koala','🐯':'tiger','🦁':'lion','🐮':'cow','🐷':'pig','🐸':'frog','🐵':'monkey','🐔':'chicken','🐧':'penguin','🐦':'bird','🐤':'chick','🦆':'duck','🦅':'eagle','🦉':'owl','🦇':'bat','🐺':'wolf','🐴':'horse','🦄':'unicorn','🐝':'bee','🦋':'butterfly','🐛':'bug','🐌':'snail','🐞':'ladybug','🐜':'ant','🕷':'spider','🦂':'scorpion','🐢':'turtle','🐍':'snake','🦎':'lizard','🦖':'t-rex','🦕':'sauropod','🐙':'octopus','🦑':'squid','🐡':'blowfish','🐠':'tropical fish','🐟':'fish','🐬':'dolphin','🐳':'whale','🦈':'shark','🐊':'crocodile','🐘':'elephant','🦛':'hippo','🦏':'rhino','🐪':'camel','🦒':'giraffe','🦘':'kangaroo','🦬':'bison','🐃':'water buffalo','🐂':'ox','🐄':'cow2','🐎':'racehorse','🐖':'pig2','🦙':'llama','🐐':'goat','🦌':'deer','🐕':'dog2','🐩':'poodle','🐈':'cat2','🦀':'crab','🦞':'lobster','🦐':'shrimp','🦪':'oyster','🌵':'cactus','🎄':'christmas tree','🌲':'evergreen','🌳':'deciduous tree','🌴':'palm tree','🌱':'seedling','🌿':'herb','☘️':'shamrock','🍀':'four leaf clover','🍃':'leaves','🍂':'fallen leaf','🍁':'maple leaf','🍄':'mushroom','🌾':'sheaf of rice','💐':'bouquet','🌷':'tulip','🌹':'rose','🥀':'wilted flower','🌺':'hibiscus','🌸':'cherry blossom','🌼':'blossom','🌻':'sunflower','🌞':'sun face','🌝':'full moon face','🌙':'crescent moon','⭐':'star','🌟':'glowing star','🌠':'shooting star','🌌':'milky way','☀️':'sun','⛅':'partly cloudy','☁️':'cloud','🌊':'wave water','❄️':'snowflake','☃️':'snowman','⛄':'snowman hat','🌈':'rainbow','⚡':'lightning',
    '🍏':'green apple','🍎':'apple','🍐':'pear','🍊':'orange','🍋':'lemon','🍌':'banana','🍉':'watermelon','🍇':'grapes','🍓':'strawberry','🫐':'blueberries','🍈':'melon','🍒':'cherries','🍑':'peach','🥭':'mango','🍍':'pineapple','🥥':'coconut','🥝':'kiwi','🍅':'tomato','🍆':'eggplant','🥑':'avocado','🥦':'broccoli','🥬':'leafy green','🥒':'cucumber','🌶':'hot pepper','🧄':'garlic','🧅':'onion','🥔':'potato','🍠':'sweet potato','🥐':'croissant','🥯':'bagel','🍞':'bread','🥖':'baguette','🥨':'pretzel','🧀':'cheese','🥚':'egg','🍳':'cooking','🧈':'butter','🥞':'pancakes','🧇':'waffle','🥓':'bacon','🥩':'meat','🍗':'chicken leg','🍖':'meat bone','🌭':'hot dog','🍔':'burger','🍟':'fries','🍕':'pizza','🥪':'sandwich','🌮':'taco','🌯':'burrito','🥗':'salad','🍝':'spaghetti','🍜':'ramen','🍲':'stew','🍛':'curry','🍣':'sushi','🍱':'bento','🥟':'dumpling','🍤':'shrimp','🍙':'rice ball','🍚':'rice','🍘':'rice cracker','🧁':'cupcake','🍰':'shortcake','🎂':'birthday cake','🍭':'lollipop','🍬':'candy','🍫':'chocolate','🍿':'popcorn','🍩':'donut','🍪':'cookie','🍯':'honey','🧃':'juice','🥤':'cup with straw','🧋':'bubble tea','🍵':'tea','☕':'coffee','🍺':'beer','🍻':'beers','🥂':'champagne','🍷':'wine','🥃':'tumbler','🍸':'cocktail','🍹':'tropical drink','🍾':'champagne bottle','🧊':'ice',
    '🚗':'car','🚕':'taxi','🚙':'suv','🚌':'bus','🏎':'racing car','🚓':'police car','🚑':'ambulance','🚒':'fire truck','🚐':'minibus','🛻':'pickup truck','🚚':'delivery truck','🚛':'truck','🚜':'tractor','🏍':'motorcycle','🛵':'scooter','🚲':'bicycle','🛴':'kick scooter','⛵':'sailboat','🚤':'speedboat','🛥':'motor boat','🚢':'ship','✈️':'airplane','🛩':'small airplane','🚁':'helicopter','🚀':'rocket','🛸':'flying saucer','🏖':'beach','🏔':'mountain snow','⛰':'mountain','🌋':'volcano','🗻':'mount fuji','🏕':'camping','🏗':'construction','🏠':'house','🏡':'house garden','🏢':'office','🏣':'post office','🏤':'european post office','🏥':'hospital','🏦':'bank','🏨':'hotel','🏩':'love hotel','🏪':'convenience store','🏫':'school','🏭':'factory','🏯':'japanese castle','🏰':'castle','💒':'wedding','🗼':'tokyo tower','🗽':'statue of liberty','⛪':'church','🕌':'mosque','🛕':'hindu temple','🕍':'synagogue','⛩':'shinto shrine','🕋':'kaaba','⛲':'fountain','🌁':'foggy','🌃':'night stars','🏙':'cityscape','🌄':'sunrise mountains','🌅':'sunrise','🌆':'city dusk','🌇':'city sunset','🌉':'bridge night','🗺':'world map','🧭':'compass','🌐':'globe','🌍':'globe africa','🌎':'globe americas','🌏':'globe asia','🪐':'planet',
    '⚽':'soccer','🏀':'basketball','🏈':'football','⚾':'baseball','🥎':'softball','🎾':'tennis','🏐':'volleyball','🏉':'rugby','🥏':'flying disc','🎱':'billiards','🏓':'ping pong','🏸':'badminton','🏒':'ice hockey','⛳':'golf','🎣':'fishing','🥊':'boxing glove','🥋':'martial arts','🎽':'running shirt','🛹':'skateboard','🛷':'sled','⛸':'ice skate','🎿':'ski','🥌':'curling stone','🏆':'trophy','🥇':'first medal','🥈':'second medal','🥉':'third medal','🏅':'sports medal','🎖':'military medal','🎪':'circus','🎭':'theater','🎨':'art palette','🎬':'clapper','🎤':'microphone','🎧':'headphones','🎼':'musical score','🎵':'musical note','🎶':'musical notes','🥁':'drum','🎷':'saxophone','🎺':'trumpet','🎸':'guitar','🎻':'violin','🎲':'game die','🎯':'bullseye','🎳':'bowling','🎮':'video game','🎰':'slot machine','🧩':'puzzle','🎴':'flower card',
    '📱':'iphone','💻':'laptop','🖥':'desktop','🖨':'printer','⌨️':'keyboard','🖱':'mouse','💽':'minidisc','💾':'floppy disk','💿':'cd','📀':'dvd','📷':'camera','📸':'camera flash','📹':'video camera','🎥':'movie camera','📞':'telephone','☎️':'old telephone','📺':'television','📻':'radio','🧭':'compass','⏱':'stopwatch','⏰':'alarm clock','⏳':'hourglass','📡':'satellite','🔋':'battery','🔌':'electric plug','💡':'light bulb','🔦':'flashlight','🕯':'candle','🛏':'bed','🚽':'toilet','🚿':'shower','🛁':'bathtub','🧹':'broom','🧺':'basket','🧻':'roll of paper','🧼':'soap','🧰':'toolbox','🔧':'wrench','🔨':'hammer','⚒':'hammer pick','🛠':'tools','⛏':'pick','🪚':'carpentry saw','🔩':'nut and bolt','🧲':'magnet','💣':'bomb','🔪':'knife','⚔️':'swords','🛡':'shield','🧪':'test tube','🧫':'petri dish','🧬':'dna','🔭':'telescope','🔬':'microscope','💊':'pill','💉':'syringe','🩺':'stethoscope','📦':'package','📫':'mailbox','📋':'clipboard','📁':'file folder','📂':'open folder','🗂':'card index dividers','📅':'calendar','📆':'tear off calendar','📇':'card index','📈':'chart up','📉':'chart down','📊':'bar chart','📌':'pushpin','📍':'round pushpin','📎':'paperclip','📏':'ruler','📐':'triangular ruler','✂️':'scissors','🔒':'locked','🔓':'unlocked','🔑':'key','🗝':'old key','💰':'money bag','💵':'dollar','💴':'yen','💶':'euro','💷':'pound','💳':'credit card','🏧':'atm','💹':'chart yen','📜':'scroll','📋':'clipboard','✏️':'pencil','✒️':'black nib','🖊':'pen','🖋':'fountain pen','📝':'memo','📓':'notebook','📔':'notebook cover','📒':'ledger','📕':'closed book','📗':'green book','📘':'blue book','📙':'orange book','📚':'books','📖':'open book','🔗':'link','📰':'newspaper','🗞':'newspaper rolled',
    '❤️':'red heart','🧡':'orange heart','💛':'yellow heart','💚':'green heart','💙':'blue heart','💜':'purple heart','🖤':'black heart','🤍':'white heart','🤎':'brown heart','💔':'broken heart','❣️':'heart exclamation','💕':'two hearts','💞':'revolving hearts','💓':'beating heart','💗':'growing heart','💖':'sparkling heart','💘':'heart arrow','💝':'heart ribbon','💟':'heart decoration','☮️':'peace','✝️':'cross','☪️':'star crescent','🕉':'om','☸️':'wheel dharma','✡️':'star david','🔯':'dotted six point star','🕎':'menorah','☯️':'yin yang','🛐':'worship','⛎':'ophiuchus','♈':'aries','♉':'taurus','♊':'gemini','♋':'cancer','♌':'leo','♍':'virgo','♎':'libra','♏':'scorpio','♐':'sagittarius','♑':'capricorn','♒':'aquarius','♓':'pisces','♻️':'recycle','✅':'check','❌':'cross','⭕':'circle','🛑':'stop','⛔':'no entry','📛':'name badge','🚫':'prohibited','💯':'hundred','❗':'exclamation','❓':'question','⚠️':'warning','🔰':'beginner','🔱':'trident','🔅':'dim button','🔆':'bright button','🔀':'shuffle','🔁':'repeat','🔂':'repeat one','▶️':'play','⏸':'pause','⏹':'stop button','⏺':'record','⏭':'next track','⏮':'previous track','⏩':'fast forward','⏪':'rewind','⬆️':'up arrow','⬇️':'down arrow','➡️':'right arrow','⬅️':'left arrow','↕️':'up down arrow','↔️':'left right arrow','↩️':'curved arrow left','↪️':'curved arrow right','🆕':'new','🆒':'cool','🆓':'free','🆗':'ok','🆙':'up','🆚':'vs','🆘':'sos','🔤':'abc','🔢':'numbers','🔠':'caps','🔡':'lowercase',
};

// ─── STATE ──────────────────────────────────────────────────────
let data = { tabs: [] };
let activeTabId = null;
let editingTabId = null;
let editMode = false;
let editingDialId = null;
let editingGroupId = null;
let editingDialGroupId = null;
let currentIconSrc = 'favicon';
let currentDialEmoji = ICONS.defaultDial;
let currentGroupEmoji = ICONS.defaultGroup;
let currentTabEmoji = ICONS.defaultTab;
let currentGroupSize  = 140; // px
let selectedFaviconUrl = ''; // currently chosen favicon in the picker
let dragSrcGroupId = null;
let dragSrcDialId = null;
let dragSrcTabId = null;
let dragSrcType = null; // 'dial' | 'group'
let pendingImageBlob = null; // image waiting to be uploaded on save
let logoAnimEnabled = true;

// Todo state
let currentTodoListEmoji = ICONS.defaultTodoList;
let activeTodoListId = null;
let editingTodoListId = null;
let editingTodoItemId = null;
